
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SmoothScroll from "./Components/SmoothScroll";

import 'swiper/css';
import 'swiper/css/pagination';
import "./globals.css";


const inter = Inter({
  weight: ['100','200','300','400','500','600','700','800','900'],
  subsets: ["latin"],
  variable: "--font-inter"

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SmoothScroll >
    <html lang="en" className="scrollbar-thin scrollbar-corner-accent scrollbar-thumb-rounded-full scrollbar-thumb-accent scrollbar-track-darker-blue">
        <body className={`bg-darker-blue ${inter.variable} `}>
         
            <main  className="">
              {children}
            </main>
      
        </body>
    </html>
    </SmoothScroll>
  );
}
//