
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SmoothScroll from "./GlobalComponents/SmoothScroll";

import 'swiper/css';
import 'swiper/css/pagination';
import "@/app/globals.css";


const inter = Inter({
  weight: ['100','200','300','400','500','600','700','800','900'],
  subsets: ["latin"],
  variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SmoothScroll root={true}>
      <html lang="en" className="scrollbar-thin scrollbar-thumb-accent scrollbar-track-darker-blue scrollbar-thumb-rounded-full">
        <body className={`bg-darker-blue ${inter.variable} `}>
            <main>
              {children}
            </main>
        </body>
      </html>
    </SmoothScroll>
  );
}
//